// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jlowellwofford/imageapi/models"
)

// DeleteContainerBynameReader is a Reader for the DeleteContainerByname structure.
type DeleteContainerBynameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteContainerBynameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteContainerBynameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteContainerBynameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteContainerBynameOK creates a DeleteContainerBynameOK with default headers values
func NewDeleteContainerBynameOK() *DeleteContainerBynameOK {
	return &DeleteContainerBynameOK{}
}

/*DeleteContainerBynameOK handles this case with default header values.

Container deleted
*/
type DeleteContainerBynameOK struct {
	Payload *models.Container
}

func (o *DeleteContainerBynameOK) Error() string {
	return fmt.Sprintf("[DELETE /container/byname/{name}][%d] deleteContainerBynameOK  %+v", 200, o.Payload)
}

func (o *DeleteContainerBynameOK) GetPayload() *models.Container {
	return o.Payload
}

func (o *DeleteContainerBynameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Container)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteContainerBynameDefault creates a DeleteContainerBynameDefault with default headers values
func NewDeleteContainerBynameDefault(code int) *DeleteContainerBynameDefault {
	return &DeleteContainerBynameDefault{
		_statusCode: code,
	}
}

/*DeleteContainerBynameDefault handles this case with default header values.

error
*/
type DeleteContainerBynameDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete container byname default response
func (o *DeleteContainerBynameDefault) Code() int {
	return o._statusCode
}

func (o *DeleteContainerBynameDefault) Error() string {
	return fmt.Sprintf("[DELETE /container/byname/{name}][%d] delete_container_byname default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteContainerBynameDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteContainerBynameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
