// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteContainerParams creates a new DeleteContainerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteContainerParams() *DeleteContainerParams {
	return &DeleteContainerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteContainerParamsWithTimeout creates a new DeleteContainerParams object
// with the ability to set a timeout on a request.
func NewDeleteContainerParamsWithTimeout(timeout time.Duration) *DeleteContainerParams {
	return &DeleteContainerParams{
		timeout: timeout,
	}
}

// NewDeleteContainerParamsWithContext creates a new DeleteContainerParams object
// with the ability to set a context for a request.
func NewDeleteContainerParamsWithContext(ctx context.Context) *DeleteContainerParams {
	return &DeleteContainerParams{
		Context: ctx,
	}
}

// NewDeleteContainerParamsWithHTTPClient creates a new DeleteContainerParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteContainerParamsWithHTTPClient(client *http.Client) *DeleteContainerParams {
	return &DeleteContainerParams{
		HTTPClient: client,
	}
}

/* DeleteContainerParams contains all the parameters to send to the API endpoint
   for the delete container operation.

   Typically these are written to a http.Request.
*/
type DeleteContainerParams struct {

	/* Force.

	   Force deletion
	*/
	Force *bool

	/* ID.

	   Delete by ID

	   Format: int64
	*/
	ID *int64

	/* Name.

	   Delete by Name
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContainerParams) WithDefaults() *DeleteContainerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete container params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteContainerParams) SetDefaults() {
	var (
		forceDefault = bool(false)
	)

	val := DeleteContainerParams{
		Force: &forceDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete container params
func (o *DeleteContainerParams) WithTimeout(timeout time.Duration) *DeleteContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete container params
func (o *DeleteContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete container params
func (o *DeleteContainerParams) WithContext(ctx context.Context) *DeleteContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete container params
func (o *DeleteContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete container params
func (o *DeleteContainerParams) WithHTTPClient(client *http.Client) *DeleteContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete container params
func (o *DeleteContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the delete container params
func (o *DeleteContainerParams) WithForce(force *bool) *DeleteContainerParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the delete container params
func (o *DeleteContainerParams) SetForce(force *bool) {
	o.Force = force
}

// WithID adds the id to the delete container params
func (o *DeleteContainerParams) WithID(id *int64) *DeleteContainerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete container params
func (o *DeleteContainerParams) SetID(id *int64) {
	o.ID = id
}

// WithName adds the name to the delete container params
func (o *DeleteContainerParams) WithName(name *string) *DeleteContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete container params
func (o *DeleteContainerParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool

		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {

			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}
	}

	if o.ID != nil {

		// query param id
		var qrID int64

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatInt64(qrID)
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
