// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jlowellwofford/imageapi/models"
)

// DeleteContainerReader is a Reader for the DeleteContainer structure.
type DeleteContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteContainerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteContainerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteContainerNoContent creates a DeleteContainerNoContent with default headers values
func NewDeleteContainerNoContent() *DeleteContainerNoContent {
	return &DeleteContainerNoContent{}
}

/*DeleteContainerNoContent handles this case with default header values.

Container deleted
*/
type DeleteContainerNoContent struct {
}

func (o *DeleteContainerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /container/{id}][%d] deleteContainerNoContent ", 204)
}

func (o *DeleteContainerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteContainerDefault creates a DeleteContainerDefault with default headers values
func NewDeleteContainerDefault(code int) *DeleteContainerDefault {
	return &DeleteContainerDefault{
		_statusCode: code,
	}
}

/*DeleteContainerDefault handles this case with default header values.

error
*/
type DeleteContainerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete container default response
func (o *DeleteContainerDefault) Code() int {
	return o._statusCode
}

func (o *DeleteContainerDefault) Error() string {
	return fmt.Sprintf("[DELETE /container/{id}][%d] delete_container default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteContainerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteContainerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
