// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jlowellwofford/imageapi/models"
)

// GetContainerBynameReader is a Reader for the GetContainerByname structure.
type GetContainerBynameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContainerBynameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContainerBynameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetContainerBynameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetContainerBynameOK creates a GetContainerBynameOK with default headers values
func NewGetContainerBynameOK() *GetContainerBynameOK {
	return &GetContainerBynameOK{}
}

/*GetContainerBynameOK handles this case with default header values.

Container entry
*/
type GetContainerBynameOK struct {
	Payload *models.Container
}

func (o *GetContainerBynameOK) Error() string {
	return fmt.Sprintf("[GET /container/byname/{name}][%d] getContainerBynameOK  %+v", 200, o.Payload)
}

func (o *GetContainerBynameOK) GetPayload() *models.Container {
	return o.Payload
}

func (o *GetContainerBynameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Container)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContainerBynameDefault creates a GetContainerBynameDefault with default headers values
func NewGetContainerBynameDefault(code int) *GetContainerBynameDefault {
	return &GetContainerBynameDefault{
		_statusCode: code,
	}
}

/*GetContainerBynameDefault handles this case with default header values.

error
*/
type GetContainerBynameDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get container byname default response
func (o *GetContainerBynameDefault) Code() int {
	return o._statusCode
}

func (o *GetContainerBynameDefault) Error() string {
	return fmt.Sprintf("[GET /container/byname/{name}][%d] get_container_byname default  %+v", o._statusCode, o.Payload)
}

func (o *GetContainerBynameDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetContainerBynameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
