// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContainerBynameParams creates a new GetContainerBynameParams object
// with the default values initialized.
func NewGetContainerBynameParams() *GetContainerBynameParams {
	var ()
	return &GetContainerBynameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContainerBynameParamsWithTimeout creates a new GetContainerBynameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContainerBynameParamsWithTimeout(timeout time.Duration) *GetContainerBynameParams {
	var ()
	return &GetContainerBynameParams{

		timeout: timeout,
	}
}

// NewGetContainerBynameParamsWithContext creates a new GetContainerBynameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContainerBynameParamsWithContext(ctx context.Context) *GetContainerBynameParams {
	var ()
	return &GetContainerBynameParams{

		Context: ctx,
	}
}

// NewGetContainerBynameParamsWithHTTPClient creates a new GetContainerBynameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContainerBynameParamsWithHTTPClient(client *http.Client) *GetContainerBynameParams {
	var ()
	return &GetContainerBynameParams{
		HTTPClient: client,
	}
}

/*GetContainerBynameParams contains all the parameters to send to the API endpoint
for the get container byname operation typically these are written to a http.Request
*/
type GetContainerBynameParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get container byname params
func (o *GetContainerBynameParams) WithTimeout(timeout time.Duration) *GetContainerBynameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get container byname params
func (o *GetContainerBynameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get container byname params
func (o *GetContainerBynameParams) WithContext(ctx context.Context) *GetContainerBynameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get container byname params
func (o *GetContainerBynameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get container byname params
func (o *GetContainerBynameParams) WithHTTPClient(client *http.Client) *GetContainerBynameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get container byname params
func (o *GetContainerBynameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get container byname params
func (o *GetContainerBynameParams) WithName(name string) *GetContainerBynameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get container byname params
func (o *GetContainerBynameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetContainerBynameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
