// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListContainersParams creates a new ListContainersParams object
// with the default values initialized.
func NewListContainersParams() *ListContainersParams {

	return &ListContainersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListContainersParamsWithTimeout creates a new ListContainersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListContainersParamsWithTimeout(timeout time.Duration) *ListContainersParams {

	return &ListContainersParams{

		timeout: timeout,
	}
}

// NewListContainersParamsWithContext creates a new ListContainersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListContainersParamsWithContext(ctx context.Context) *ListContainersParams {

	return &ListContainersParams{

		Context: ctx,
	}
}

// NewListContainersParamsWithHTTPClient creates a new ListContainersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListContainersParamsWithHTTPClient(client *http.Client) *ListContainersParams {

	return &ListContainersParams{
		HTTPClient: client,
	}
}

/*ListContainersParams contains all the parameters to send to the API endpoint
for the list containers operation typically these are written to a http.Request
*/
type ListContainersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list containers params
func (o *ListContainersParams) WithTimeout(timeout time.Duration) *ListContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list containers params
func (o *ListContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list containers params
func (o *ListContainersParams) WithContext(ctx context.Context) *ListContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list containers params
func (o *ListContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list containers params
func (o *ListContainersParams) WithHTTPClient(client *http.Client) *ListContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list containers params
func (o *ListContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
