// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jlowellwofford/imageapi/models"
)

// SetContainerStateBynameReader is a Reader for the SetContainerStateByname structure.
type SetContainerStateBynameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetContainerStateBynameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetContainerStateBynameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSetContainerStateBynameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSetContainerStateBynameOK creates a SetContainerStateBynameOK with default headers values
func NewSetContainerStateBynameOK() *SetContainerStateBynameOK {
	return &SetContainerStateBynameOK{}
}

/*SetContainerStateBynameOK handles this case with default header values.

Container state changed
*/
type SetContainerStateBynameOK struct {
	Payload *models.Container
}

func (o *SetContainerStateBynameOK) Error() string {
	return fmt.Sprintf("[GET /container/byname/{name}/{state}][%d] setContainerStateBynameOK  %+v", 200, o.Payload)
}

func (o *SetContainerStateBynameOK) GetPayload() *models.Container {
	return o.Payload
}

func (o *SetContainerStateBynameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Container)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetContainerStateBynameDefault creates a SetContainerStateBynameDefault with default headers values
func NewSetContainerStateBynameDefault(code int) *SetContainerStateBynameDefault {
	return &SetContainerStateBynameDefault{
		_statusCode: code,
	}
}

/*SetContainerStateBynameDefault handles this case with default header values.

error
*/
type SetContainerStateBynameDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the set container state byname default response
func (o *SetContainerStateBynameDefault) Code() int {
	return o._statusCode
}

func (o *SetContainerStateBynameDefault) Error() string {
	return fmt.Sprintf("[GET /container/byname/{name}/{state}][%d] set_container_state_byname default  %+v", o._statusCode, o.Payload)
}

func (o *SetContainerStateBynameDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetContainerStateBynameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
