// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetContainerStateBynameParams creates a new SetContainerStateBynameParams object
// with the default values initialized.
func NewSetContainerStateBynameParams() *SetContainerStateBynameParams {
	var ()
	return &SetContainerStateBynameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetContainerStateBynameParamsWithTimeout creates a new SetContainerStateBynameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetContainerStateBynameParamsWithTimeout(timeout time.Duration) *SetContainerStateBynameParams {
	var ()
	return &SetContainerStateBynameParams{

		timeout: timeout,
	}
}

// NewSetContainerStateBynameParamsWithContext creates a new SetContainerStateBynameParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetContainerStateBynameParamsWithContext(ctx context.Context) *SetContainerStateBynameParams {
	var ()
	return &SetContainerStateBynameParams{

		Context: ctx,
	}
}

// NewSetContainerStateBynameParamsWithHTTPClient creates a new SetContainerStateBynameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetContainerStateBynameParamsWithHTTPClient(client *http.Client) *SetContainerStateBynameParams {
	var ()
	return &SetContainerStateBynameParams{
		HTTPClient: client,
	}
}

/*SetContainerStateBynameParams contains all the parameters to send to the API endpoint
for the set container state byname operation typically these are written to a http.Request
*/
type SetContainerStateBynameParams struct {

	/*Name*/
	Name string
	/*State*/
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set container state byname params
func (o *SetContainerStateBynameParams) WithTimeout(timeout time.Duration) *SetContainerStateBynameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set container state byname params
func (o *SetContainerStateBynameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set container state byname params
func (o *SetContainerStateBynameParams) WithContext(ctx context.Context) *SetContainerStateBynameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set container state byname params
func (o *SetContainerStateBynameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set container state byname params
func (o *SetContainerStateBynameParams) WithHTTPClient(client *http.Client) *SetContainerStateBynameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set container state byname params
func (o *SetContainerStateBynameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the set container state byname params
func (o *SetContainerStateBynameParams) WithName(name string) *SetContainerStateBynameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set container state byname params
func (o *SetContainerStateBynameParams) SetName(name string) {
	o.Name = name
}

// WithState adds the state to the set container state byname params
func (o *SetContainerStateBynameParams) WithState(state string) *SetContainerStateBynameParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the set container state byname params
func (o *SetContainerStateBynameParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *SetContainerStateBynameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param state
	if err := r.SetPathParam("state", o.State); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
