// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSetContainerStateParams creates a new SetContainerStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetContainerStateParams() *SetContainerStateParams {
	return &SetContainerStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetContainerStateParamsWithTimeout creates a new SetContainerStateParams object
// with the ability to set a timeout on a request.
func NewSetContainerStateParamsWithTimeout(timeout time.Duration) *SetContainerStateParams {
	return &SetContainerStateParams{
		timeout: timeout,
	}
}

// NewSetContainerStateParamsWithContext creates a new SetContainerStateParams object
// with the ability to set a context for a request.
func NewSetContainerStateParamsWithContext(ctx context.Context) *SetContainerStateParams {
	return &SetContainerStateParams{
		Context: ctx,
	}
}

// NewSetContainerStateParamsWithHTTPClient creates a new SetContainerStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetContainerStateParamsWithHTTPClient(client *http.Client) *SetContainerStateParams {
	return &SetContainerStateParams{
		HTTPClient: client,
	}
}

/* SetContainerStateParams contains all the parameters to send to the API endpoint
   for the set container state operation.

   Typically these are written to a http.Request.
*/
type SetContainerStateParams struct {

	/* ID.

	   ID of container

	   Format: int64
	*/
	ID *int64

	/* Name.

	   Name of container
	*/
	Name *string

	/* State.

	   Desired container state
	*/
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set container state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetContainerStateParams) WithDefaults() *SetContainerStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set container state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetContainerStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set container state params
func (o *SetContainerStateParams) WithTimeout(timeout time.Duration) *SetContainerStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set container state params
func (o *SetContainerStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set container state params
func (o *SetContainerStateParams) WithContext(ctx context.Context) *SetContainerStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set container state params
func (o *SetContainerStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set container state params
func (o *SetContainerStateParams) WithHTTPClient(client *http.Client) *SetContainerStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set container state params
func (o *SetContainerStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the set container state params
func (o *SetContainerStateParams) WithID(id *int64) *SetContainerStateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set container state params
func (o *SetContainerStateParams) SetID(id *int64) {
	o.ID = id
}

// WithName adds the name to the set container state params
func (o *SetContainerStateParams) WithName(name *string) *SetContainerStateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set container state params
func (o *SetContainerStateParams) SetName(name *string) {
	o.Name = name
}

// WithState adds the state to the set container state params
func (o *SetContainerStateParams) WithState(state string) *SetContainerStateParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the set container state params
func (o *SetContainerStateParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *SetContainerStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID int64

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatInt64(qrID)
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	// query param state
	qrState := o.State
	qState := qrState
	if qState != "" {

		if err := r.SetQueryParam("state", qState); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
