// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMountRbdHandlerFunc turns a function with the right signature into a get mount rbd handler
type GetMountRbdHandlerFunc func(GetMountRbdParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMountRbdHandlerFunc) Handle(params GetMountRbdParams) middleware.Responder {
	return fn(params)
}

// GetMountRbdHandler interface for that can handle valid get mount rbd params
type GetMountRbdHandler interface {
	Handle(GetMountRbdParams) middleware.Responder
}

// NewGetMountRbd creates a new http.Handler for the get mount rbd operation
func NewGetMountRbd(ctx *middleware.Context, handler GetMountRbdHandler) *GetMountRbd {
	return &GetMountRbd{Context: ctx, Handler: handler}
}

/*GetMountRbd swagger:route GET /mount/rbd/{id} mounts getMountRbd

GetMountRbd get mount rbd API

*/
type GetMountRbd struct {
	Context *middleware.Context
	Handler GetMountRbdHandler
}

func (o *GetMountRbd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMountRbdParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
