// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListMountsHandlerFunc turns a function with the right signature into a list mounts handler
type ListMountsHandlerFunc func(ListMountsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListMountsHandlerFunc) Handle(params ListMountsParams) middleware.Responder {
	return fn(params)
}

// ListMountsHandler interface for that can handle valid list mounts params
type ListMountsHandler interface {
	Handle(ListMountsParams) middleware.Responder
}

// NewListMounts creates a new http.Handler for the list mounts operation
func NewListMounts(ctx *middleware.Context, handler ListMountsHandler) *ListMounts {
	return &ListMounts{Context: ctx, Handler: handler}
}

/*ListMounts swagger:route GET /mount mounts listMounts

List mounts

*/
type ListMounts struct {
	Context *middleware.Context
	Handler ListMountsHandler
}

func (o *ListMounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListMountsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
