// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jlowellwofford/imageapi/models"
)

// ListMountsOKCode is the HTTP code returned for type ListMountsOK
const ListMountsOKCode int = 200

/*ListMountsOK list all mounts

swagger:response listMountsOK
*/
type ListMountsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Mount `json:"body,omitempty"`
}

// NewListMountsOK creates ListMountsOK with default headers values
func NewListMountsOK() *ListMountsOK {

	return &ListMountsOK{}
}

// WithPayload adds the payload to the list mounts o k response
func (o *ListMountsOK) WithPayload(payload []*models.Mount) *ListMountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list mounts o k response
func (o *ListMountsOK) SetPayload(payload []*models.Mount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Mount, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListMountsDefault error

swagger:response listMountsDefault
*/
type ListMountsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListMountsDefault creates ListMountsDefault with default headers values
func NewListMountsDefault(code int) *ListMountsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListMountsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list mounts default response
func (o *ListMountsDefault) WithStatusCode(code int) *ListMountsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list mounts default response
func (o *ListMountsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list mounts default response
func (o *ListMountsDefault) WithPayload(payload *models.Error) *ListMountsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list mounts default response
func (o *ListMountsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMountsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
