// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewListMountsParams creates a new ListMountsParams object
//
// There are no default values defined in the spec.
func NewListMountsParams() ListMountsParams {

	return ListMountsParams{}
}

// ListMountsParams contains all the bound params for the list mounts operation
// typically these are obtained from a http.Request
//
// swagger:parameters list_mounts
type ListMountsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of a single mount to query.
	  In: query
	*/
	ID *int64
	/*Kind of mounts to query.
	  In: query
	*/
	Kind *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListMountsParams() beforehand.
func (o *ListMountsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qID, qhkID, _ := qs.GetOK("id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qKind, qhkKind, _ := qs.GetOK("kind")
	if err := o.bindKind(qKind, qhkKind, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from query.
func (o *ListMountsParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "query", "int64", raw)
	}
	o.ID = &value

	return nil
}

// bindKind binds and validates parameter Kind from query.
func (o *ListMountsParams) bindKind(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Kind = &raw

	if err := o.validateKind(formats); err != nil {
		return err
	}

	return nil
}

// validateKind carries on validations for parameter Kind
func (o *ListMountsParams) validateKind(formats strfmt.Registry) error {

	if err := validate.EnumCase("kind", "query", *o.Kind, []interface{}{"attach", "bind", "nfs", "overlay", "uri"}, true); err != nil {
		return err
	}

	return nil
}
