// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// MountHandlerFunc turns a function with the right signature into a mount handler
type MountHandlerFunc func(MountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MountHandlerFunc) Handle(params MountParams) middleware.Responder {
	return fn(params)
}

// MountHandler interface for that can handle valid mount params
type MountHandler interface {
	Handle(MountParams) middleware.Responder
}

// NewMount creates a new http.Handler for the mount operation
func NewMount(ctx *middleware.Context, handler MountHandler) *Mount {
	return &Mount{Context: ctx, Handler: handler}
}

/*Mount swagger:route POST /mount mounts mount

Create a new mount by mount specification.

*/
type Mount struct {
	Context *middleware.Context
	Handler MountHandler
}

func (o *Mount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
