// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jlowellwofford/imageapi/models"
)

// UnmountRbdNoContentCode is the HTTP code returned for type UnmountRbdNoContent
const UnmountRbdNoContentCode int = 204

/*UnmountRbdNoContent Unmounted

swagger:response unmountRbdNoContent
*/
type UnmountRbdNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.MountRbd `json:"body,omitempty"`
}

// NewUnmountRbdNoContent creates UnmountRbdNoContent with default headers values
func NewUnmountRbdNoContent() *UnmountRbdNoContent {

	return &UnmountRbdNoContent{}
}

// WithPayload adds the payload to the unmount rbd no content response
func (o *UnmountRbdNoContent) WithPayload(payload *models.MountRbd) *UnmountRbdNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unmount rbd no content response
func (o *UnmountRbdNoContent) SetPayload(payload *models.MountRbd) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnmountRbdNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UnmountRbdDefault error

swagger:response unmountRbdDefault
*/
type UnmountRbdDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnmountRbdDefault creates UnmountRbdDefault with default headers values
func NewUnmountRbdDefault(code int) *UnmountRbdDefault {
	if code <= 0 {
		code = 500
	}

	return &UnmountRbdDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the unmount rbd default response
func (o *UnmountRbdDefault) WithStatusCode(code int) *UnmountRbdDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the unmount rbd default response
func (o *UnmountRbdDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the unmount rbd default response
func (o *UnmountRbdDefault) WithPayload(payload *models.Error) *UnmountRbdDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unmount rbd default response
func (o *UnmountRbdDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnmountRbdDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
