// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jlowellwofford/imageapi/models"
)

// UnmountOverlayNoContentCode is the HTTP code returned for type UnmountOverlayNoContent
const UnmountOverlayNoContentCode int = 204

/*UnmountOverlayNoContent Unmounted

swagger:response unmountOverlayNoContent
*/
type UnmountOverlayNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.MountOverlay `json:"body,omitempty"`
}

// NewUnmountOverlayNoContent creates UnmountOverlayNoContent with default headers values
func NewUnmountOverlayNoContent() *UnmountOverlayNoContent {

	return &UnmountOverlayNoContent{}
}

// WithPayload adds the payload to the unmount overlay no content response
func (o *UnmountOverlayNoContent) WithPayload(payload *models.MountOverlay) *UnmountOverlayNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unmount overlay no content response
func (o *UnmountOverlayNoContent) SetPayload(payload *models.MountOverlay) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnmountOverlayNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UnmountOverlayDefault error

swagger:response unmountOverlayDefault
*/
type UnmountOverlayDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUnmountOverlayDefault creates UnmountOverlayDefault with default headers values
func NewUnmountOverlayDefault(code int) *UnmountOverlayDefault {
	if code <= 0 {
		code = 500
	}

	return &UnmountOverlayDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the unmount overlay default response
func (o *UnmountOverlayDefault) WithStatusCode(code int) *UnmountOverlayDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the unmount overlay default response
func (o *UnmountOverlayDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the unmount overlay default response
func (o *UnmountOverlayDefault) WithPayload(payload *models.Error) *UnmountOverlayDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unmount overlay default response
func (o *UnmountOverlayDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnmountOverlayDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
