// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Image API
//
//  Mange system image containers
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /imageapi/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
