// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kraken-hpc/imageapi/models"
)

// AttachReader is a Reader for the Attach structure.
type AttachReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttachReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAttachCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAttachDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAttachCreated creates a AttachCreated with default headers values
func NewAttachCreated() *AttachCreated {
	return &AttachCreated{}
}

/* AttachCreated describes a response with status code 201, with default header values.

attach succeed
*/
type AttachCreated struct {
	Payload *models.Attach
}

func (o *AttachCreated) Error() string {
	return fmt.Sprintf("[POST /attach][%d] attachCreated  %+v", 201, o.Payload)
}
func (o *AttachCreated) GetPayload() *models.Attach {
	return o.Payload
}

func (o *AttachCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attach)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAttachDefault creates a AttachDefault with default headers values
func NewAttachDefault(code int) *AttachDefault {
	return &AttachDefault{
		_statusCode: code,
	}
}

/* AttachDefault describes a response with status code -1, with default header values.

error
*/
type AttachDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the attach default response
func (o *AttachDefault) Code() int {
	return o._statusCode
}

func (o *AttachDefault) Error() string {
	return fmt.Sprintf("[POST /attach][%d] attach default  %+v", o._statusCode, o.Payload)
}
func (o *AttachDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *AttachDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
