// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kraken-hpc/imageapi/models"
)

// ListAttachmentsReader is a Reader for the ListAttachments structure.
type ListAttachmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAttachmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAttachmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListAttachmentsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListAttachmentsOK creates a ListAttachmentsOK with default headers values
func NewListAttachmentsOK() *ListAttachmentsOK {
	return &ListAttachmentsOK{}
}

/* ListAttachmentsOK describes a response with status code 200, with default header values.

list all attachments
*/
type ListAttachmentsOK struct {
	Payload []*models.Attach
}

func (o *ListAttachmentsOK) Error() string {
	return fmt.Sprintf("[GET /attach][%d] listAttachmentsOK  %+v", 200, o.Payload)
}
func (o *ListAttachmentsOK) GetPayload() []*models.Attach {
	return o.Payload
}

func (o *ListAttachmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAttachmentsDefault creates a ListAttachmentsDefault with default headers values
func NewListAttachmentsDefault(code int) *ListAttachmentsDefault {
	return &ListAttachmentsDefault{
		_statusCode: code,
	}
}

/* ListAttachmentsDefault describes a response with status code -1, with default header values.

error
*/
type ListAttachmentsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list attachments default response
func (o *ListAttachmentsDefault) Code() int {
	return o._statusCode
}

func (o *ListAttachmentsDefault) Error() string {
	return fmt.Sprintf("[GET /attach][%d] list_attachments default  %+v", o._statusCode, o.Payload)
}
func (o *ListAttachmentsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListAttachmentsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
