// Code generated by go-swagger; DO NOT EDIT.

package attach

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kraken-hpc/imageapi/models"
)

// GetRbdReader is a Reader for the GetRbd structure.
type GetRbdReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRbdReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRbdOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetRbdDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRbdOK creates a GetRbdOK with default headers values
func NewGetRbdOK() *GetRbdOK {
	return &GetRbdOK{}
}

/*GetRbdOK handles this case with default header values.

RBD entry
*/
type GetRbdOK struct {
	Payload *models.Rbd
}

func (o *GetRbdOK) Error() string {
	return fmt.Sprintf("[GET /attach/rbd/{id}][%d] getRbdOK  %+v", 200, o.Payload)
}

func (o *GetRbdOK) GetPayload() *models.Rbd {
	return o.Payload
}

func (o *GetRbdOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rbd)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRbdDefault creates a GetRbdDefault with default headers values
func NewGetRbdDefault(code int) *GetRbdDefault {
	return &GetRbdDefault{
		_statusCode: code,
	}
}

/*GetRbdDefault handles this case with default header values.

error
*/
type GetRbdDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get rbd default response
func (o *GetRbdDefault) Code() int {
	return o._statusCode
}

func (o *GetRbdDefault) Error() string {
	return fmt.Sprintf("[GET /attach/rbd/{id}][%d] get_rbd default  %+v", o._statusCode, o.Payload)
}

func (o *GetRbdDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRbdDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
