// Code generated by go-swagger; DO NOT EDIT.

package attach

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kraken-hpc/imageapi/models"
)

// UnmapRbdReader is a Reader for the UnmapRbd structure.
type UnmapRbdReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnmapRbdReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnmapRbdOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUnmapRbdDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUnmapRbdOK creates a UnmapRbdOK with default headers values
func NewUnmapRbdOK() *UnmapRbdOK {
	return &UnmapRbdOK{}
}

/*UnmapRbdOK handles this case with default header values.

Unmapped
*/
type UnmapRbdOK struct {
	Payload *models.Rbd
}

func (o *UnmapRbdOK) Error() string {
	return fmt.Sprintf("[DELETE /attach/rbd/{id}][%d] unmapRbdOK  %+v", 200, o.Payload)
}

func (o *UnmapRbdOK) GetPayload() *models.Rbd {
	return o.Payload
}

func (o *UnmapRbdOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rbd)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnmapRbdDefault creates a UnmapRbdDefault with default headers values
func NewUnmapRbdDefault(code int) *UnmapRbdDefault {
	return &UnmapRbdDefault{
		_statusCode: code,
	}
}

/*UnmapRbdDefault handles this case with default header values.

error
*/
type UnmapRbdDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the unmap rbd default response
func (o *UnmapRbdDefault) Code() int {
	return o._statusCode
}

func (o *UnmapRbdDefault) Error() string {
	return fmt.Sprintf("[DELETE /attach/rbd/{id}][%d] unmap_rbd default  %+v", o._statusCode, o.Payload)
}

func (o *UnmapRbdDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnmapRbdDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
