// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jlowellwofford/imageapi/models"
)

// DeleteContainerBynameNoContentCode is the HTTP code returned for type DeleteContainerBynameNoContent
const DeleteContainerBynameNoContentCode int = 204

/*DeleteContainerBynameNoContent Container deleted

swagger:response deleteContainerBynameNoContent
*/
type DeleteContainerBynameNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Container `json:"body,omitempty"`
}

// NewDeleteContainerBynameNoContent creates DeleteContainerBynameNoContent with default headers values
func NewDeleteContainerBynameNoContent() *DeleteContainerBynameNoContent {

	return &DeleteContainerBynameNoContent{}
}

// WithPayload adds the payload to the delete container byname no content response
func (o *DeleteContainerBynameNoContent) WithPayload(payload *models.Container) *DeleteContainerBynameNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete container byname no content response
func (o *DeleteContainerBynameNoContent) SetPayload(payload *models.Container) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteContainerBynameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteContainerBynameDefault error

swagger:response deleteContainerBynameDefault
*/
type DeleteContainerBynameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteContainerBynameDefault creates DeleteContainerBynameDefault with default headers values
func NewDeleteContainerBynameDefault(code int) *DeleteContainerBynameDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteContainerBynameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete container byname default response
func (o *DeleteContainerBynameDefault) WithStatusCode(code int) *DeleteContainerBynameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete container byname default response
func (o *DeleteContainerBynameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete container byname default response
func (o *DeleteContainerBynameDefault) WithPayload(payload *models.Error) *DeleteContainerBynameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete container byname default response
func (o *DeleteContainerBynameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteContainerBynameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
