// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jlowellwofford/imageapi/models"
)

// GetContainerBynameOKCode is the HTTP code returned for type GetContainerBynameOK
const GetContainerBynameOKCode int = 200

/*GetContainerBynameOK Container entry

swagger:response getContainerBynameOK
*/
type GetContainerBynameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Container `json:"body,omitempty"`
}

// NewGetContainerBynameOK creates GetContainerBynameOK with default headers values
func NewGetContainerBynameOK() *GetContainerBynameOK {

	return &GetContainerBynameOK{}
}

// WithPayload adds the payload to the get container byname o k response
func (o *GetContainerBynameOK) WithPayload(payload *models.Container) *GetContainerBynameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container byname o k response
func (o *GetContainerBynameOK) SetPayload(payload *models.Container) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerBynameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetContainerBynameDefault error

swagger:response getContainerBynameDefault
*/
type GetContainerBynameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetContainerBynameDefault creates GetContainerBynameDefault with default headers values
func NewGetContainerBynameDefault(code int) *GetContainerBynameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetContainerBynameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get container byname default response
func (o *GetContainerBynameDefault) WithStatusCode(code int) *GetContainerBynameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get container byname default response
func (o *GetContainerBynameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get container byname default response
func (o *GetContainerBynameDefault) WithPayload(payload *models.Error) *GetContainerBynameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get container byname default response
func (o *GetContainerBynameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContainerBynameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
