// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetContainerStateBynameHandlerFunc turns a function with the right signature into a set container state byname handler
type SetContainerStateBynameHandlerFunc func(SetContainerStateBynameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SetContainerStateBynameHandlerFunc) Handle(params SetContainerStateBynameParams) middleware.Responder {
	return fn(params)
}

// SetContainerStateBynameHandler interface for that can handle valid set container state byname params
type SetContainerStateBynameHandler interface {
	Handle(SetContainerStateBynameParams) middleware.Responder
}

// NewSetContainerStateByname creates a new http.Handler for the set container state byname operation
func NewSetContainerStateByname(ctx *middleware.Context, handler SetContainerStateBynameHandler) *SetContainerStateByname {
	return &SetContainerStateByname{Context: ctx, Handler: handler}
}

/*SetContainerStateByname swagger:route GET /container/byname/{name}/{state} containers setContainerStateByname

Request a (valid) state for a container.
Valid states to request include: `running`, `exited`, `paused` (paused is not yet implemented)


*/
type SetContainerStateByname struct {
	Context *middleware.Context
	Handler SetContainerStateBynameHandler
}

func (o *SetContainerStateByname) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetContainerStateBynameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
