// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAttachHandlerFunc turns a function with the right signature into a delete attach handler
type DeleteAttachHandlerFunc func(DeleteAttachParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAttachHandlerFunc) Handle(params DeleteAttachParams) middleware.Responder {
	return fn(params)
}

// DeleteAttachHandler interface for that can handle valid delete attach params
type DeleteAttachHandler interface {
	Handle(DeleteAttachParams) middleware.Responder
}

// NewDeleteAttach creates a new http.Handler for the delete attach operation
func NewDeleteAttach(ctx *middleware.Context, handler DeleteAttachHandler) *DeleteAttach {
	return &DeleteAttach{Context: ctx, Handler: handler}
}

/* DeleteAttach swagger:route DELETE /attach attachments deleteAttach

Detach a specified attachment.

*/
type DeleteAttach struct {
	Context *middleware.Context
	Handler DeleteAttachHandler
}

func (o *DeleteAttach) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAttachParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
