// Code generated by go-swagger; DO NOT EDIT.

package attachments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListAttachmentsHandlerFunc turns a function with the right signature into a list attachments handler
type ListAttachmentsHandlerFunc func(ListAttachmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAttachmentsHandlerFunc) Handle(params ListAttachmentsParams) middleware.Responder {
	return fn(params)
}

// ListAttachmentsHandler interface for that can handle valid list attachments params
type ListAttachmentsHandler interface {
	Handle(ListAttachmentsParams) middleware.Responder
}

// NewListAttachments creates a new http.Handler for the list attachments operation
func NewListAttachments(ctx *middleware.Context, handler ListAttachmentsHandler) *ListAttachments {
	return &ListAttachments{Context: ctx, Handler: handler}
}

/* ListAttachments swagger:route GET /attach attachments listAttachments

List attachments

*/
type ListAttachments struct {
	Context *middleware.Context
	Handler ListAttachmentsHandler
}

func (o *ListAttachments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListAttachmentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
