// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteMountParams creates a new DeleteMountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMountParams() *DeleteMountParams {
	return &DeleteMountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMountParamsWithTimeout creates a new DeleteMountParams object
// with the ability to set a timeout on a request.
func NewDeleteMountParamsWithTimeout(timeout time.Duration) *DeleteMountParams {
	return &DeleteMountParams{
		timeout: timeout,
	}
}

// NewDeleteMountParamsWithContext creates a new DeleteMountParams object
// with the ability to set a context for a request.
func NewDeleteMountParamsWithContext(ctx context.Context) *DeleteMountParams {
	return &DeleteMountParams{
		Context: ctx,
	}
}

// NewDeleteMountParamsWithHTTPClient creates a new DeleteMountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMountParamsWithHTTPClient(client *http.Client) *DeleteMountParams {
	return &DeleteMountParams{
		HTTPClient: client,
	}
}

/* DeleteMountParams contains all the parameters to send to the API endpoint
   for the delete mount operation.

   Typically these are written to a http.Request.
*/
type DeleteMountParams struct {

	/* ID.

	   ID of mount to delete

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete mount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMountParams) WithDefaults() *DeleteMountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete mount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete mount params
func (o *DeleteMountParams) WithTimeout(timeout time.Duration) *DeleteMountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mount params
func (o *DeleteMountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mount params
func (o *DeleteMountParams) WithContext(ctx context.Context) *DeleteMountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mount params
func (o *DeleteMountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mount params
func (o *DeleteMountParams) WithHTTPClient(client *http.Client) *DeleteMountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mount params
func (o *DeleteMountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete mount params
func (o *DeleteMountParams) WithID(id int64) *DeleteMountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete mount params
func (o *DeleteMountParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
