// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new mounts API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for mounts API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteMount(params *DeleteMountParams, opts ...ClientOption) (*DeleteMountOK, error)

	ListMounts(params *ListMountsParams, opts ...ClientOption) (*ListMountsOK, error)

	Mount(params *MountParams, opts ...ClientOption) (*MountCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeleteMount Unmount a specified mount.  Note that mount reference IDs must be specified.
*/
func (a *Client) DeleteMount(params *DeleteMountParams, opts ...ClientOption) (*DeleteMountOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMountParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteMount",
		Method:             "DELETE",
		PathPattern:        "/mount",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteMountReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteMountOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteMountDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ListMounts List mounts
*/
func (a *Client) ListMounts(params *ListMountsParams, opts ...ClientOption) (*ListMountsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMountsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "list_mounts",
		Method:             "GET",
		PathPattern:        "/mount",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListMountsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListMountsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListMountsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  Mount Create a new mount by mount specification.
*/
func (a *Client) Mount(params *MountParams, opts ...ClientOption) (*MountCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewMountParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "mount",
		Method:             "POST",
		PathPattern:        "/mount",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &MountReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*MountCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*MountDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
