// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kraken-hpc/imageapi/models"
)

// NewMountParams creates a new MountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMountParams() *MountParams {
	return &MountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMountParamsWithTimeout creates a new MountParams object
// with the ability to set a timeout on a request.
func NewMountParamsWithTimeout(timeout time.Duration) *MountParams {
	return &MountParams{
		timeout: timeout,
	}
}

// NewMountParamsWithContext creates a new MountParams object
// with the ability to set a context for a request.
func NewMountParamsWithContext(ctx context.Context) *MountParams {
	return &MountParams{
		Context: ctx,
	}
}

// NewMountParamsWithHTTPClient creates a new MountParams object
// with the ability to set a custom HTTPClient for a request.
func NewMountParamsWithHTTPClient(client *http.Client) *MountParams {
	return &MountParams{
		HTTPClient: client,
	}
}

/* MountParams contains all the parameters to send to the API endpoint
   for the mount operation.

   Typically these are written to a http.Request.
*/
type MountParams struct {

	// Mount.
	Mount *models.Mount

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the mount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MountParams) WithDefaults() *MountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the mount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the mount params
func (o *MountParams) WithTimeout(timeout time.Duration) *MountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mount params
func (o *MountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mount params
func (o *MountParams) WithContext(ctx context.Context) *MountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mount params
func (o *MountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mount params
func (o *MountParams) WithHTTPClient(client *http.Client) *MountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mount params
func (o *MountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMount adds the mount to the mount params
func (o *MountParams) WithMount(mount *models.Mount) *MountParams {
	o.SetMount(mount)
	return o
}

// SetMount adds the mount to the mount params
func (o *MountParams) SetMount(mount *models.Mount) {
	o.Mount = mount
}

// WriteToRequest writes these params to a swagger request
func (o *MountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Mount != nil {
		if err := r.SetBodyParam(o.Mount); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
