// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jlowellwofford/imageapi/models"
)

// NewMountOverlayParams creates a new MountOverlayParams object
// with the default values initialized.
func NewMountOverlayParams() *MountOverlayParams {
	var ()
	return &MountOverlayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMountOverlayParamsWithTimeout creates a new MountOverlayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMountOverlayParamsWithTimeout(timeout time.Duration) *MountOverlayParams {
	var ()
	return &MountOverlayParams{

		timeout: timeout,
	}
}

// NewMountOverlayParamsWithContext creates a new MountOverlayParams object
// with the default values initialized, and the ability to set a context for a request
func NewMountOverlayParamsWithContext(ctx context.Context) *MountOverlayParams {
	var ()
	return &MountOverlayParams{

		Context: ctx,
	}
}

// NewMountOverlayParamsWithHTTPClient creates a new MountOverlayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMountOverlayParamsWithHTTPClient(client *http.Client) *MountOverlayParams {
	var ()
	return &MountOverlayParams{
		HTTPClient: client,
	}
}

/*MountOverlayParams contains all the parameters to send to the API endpoint
for the mount overlay operation typically these are written to a http.Request
*/
type MountOverlayParams struct {

	/*Mount*/
	Mount *models.MountOverlay

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mount overlay params
func (o *MountOverlayParams) WithTimeout(timeout time.Duration) *MountOverlayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mount overlay params
func (o *MountOverlayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mount overlay params
func (o *MountOverlayParams) WithContext(ctx context.Context) *MountOverlayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mount overlay params
func (o *MountOverlayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mount overlay params
func (o *MountOverlayParams) WithHTTPClient(client *http.Client) *MountOverlayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mount overlay params
func (o *MountOverlayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMount adds the mount to the mount overlay params
func (o *MountOverlayParams) WithMount(mount *models.MountOverlay) *MountOverlayParams {
	o.SetMount(mount)
	return o
}

// SetMount adds the mount to the mount overlay params
func (o *MountOverlayParams) SetMount(mount *models.MountOverlay) {
	o.Mount = mount
}

// WriteToRequest writes these params to a swagger request
func (o *MountOverlayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Mount != nil {
		if err := r.SetBodyParam(o.Mount); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
