// Code generated by go-swagger; DO NOT EDIT.

package mounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUnmountRbdParams creates a new UnmountRbdParams object
// with the default values initialized.
func NewUnmountRbdParams() *UnmountRbdParams {
	var ()
	return &UnmountRbdParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnmountRbdParamsWithTimeout creates a new UnmountRbdParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnmountRbdParamsWithTimeout(timeout time.Duration) *UnmountRbdParams {
	var ()
	return &UnmountRbdParams{

		timeout: timeout,
	}
}

// NewUnmountRbdParamsWithContext creates a new UnmountRbdParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnmountRbdParamsWithContext(ctx context.Context) *UnmountRbdParams {
	var ()
	return &UnmountRbdParams{

		Context: ctx,
	}
}

// NewUnmountRbdParamsWithHTTPClient creates a new UnmountRbdParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnmountRbdParamsWithHTTPClient(client *http.Client) *UnmountRbdParams {
	var ()
	return &UnmountRbdParams{
		HTTPClient: client,
	}
}

/*UnmountRbdParams contains all the parameters to send to the API endpoint
for the unmount rbd operation typically these are written to a http.Request
*/
type UnmountRbdParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unmount rbd params
func (o *UnmountRbdParams) WithTimeout(timeout time.Duration) *UnmountRbdParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unmount rbd params
func (o *UnmountRbdParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unmount rbd params
func (o *UnmountRbdParams) WithContext(ctx context.Context) *UnmountRbdParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unmount rbd params
func (o *UnmountRbdParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unmount rbd params
func (o *UnmountRbdParams) WithHTTPClient(client *http.Client) *UnmountRbdParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unmount rbd params
func (o *UnmountRbdParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the unmount rbd params
func (o *UnmountRbdParams) WithID(id int64) *UnmountRbdParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the unmount rbd params
func (o *UnmountRbdParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UnmountRbdParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
