// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MountOverlay `mount_overlay` describes an Overlayfs mount.  All mount points must be RBD ID's.
// At very least, `lower` must be specified.  If `upper` length is zero, no `upper`
// mounts will be used.  `workdir` will be assigned automatically.
//
// If the mounts specified in `lower` are specifications and not ID references, they
// will be recursively mounted/attached.
//
// Overlay mounts are identified by their uppermost `lower` ID.
//
//
// swagger:model mount_overlay
type MountOverlay struct {

	// id
	// Read Only: true
	ID ID `json:"id,omitempty"`

	// This is an array of mount specifications to be used (in order) as lower mounts for the overlay.
	// Required: true
	Lower []*Mount `json:"lower"`

	// mountpoint
	// Read Only: true
	Mountpoint string `json:"mountpoint,omitempty"`

	// ref
	// Read Only: true
	Ref int64 `json:"ref,omitempty"`

	// currently, upperdir is always a directory in mountDir
	// Read Only: true
	Upperdir string `json:"upperdir,omitempty"`

	// workdir
	// Read Only: true
	Workdir string `json:"workdir,omitempty"`
}

// Validate validates this mount overlay
func (m *MountOverlay) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLower(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MountOverlay) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := m.ID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("id")
		}
		return err
	}

	return nil
}

func (m *MountOverlay) validateLower(formats strfmt.Registry) error {

	if err := validate.Required("lower", "body", m.Lower); err != nil {
		return err
	}

	for i := 0; i < len(m.Lower); i++ {
		if swag.IsZero(m.Lower[i]) { // not required
			continue
		}

		if m.Lower[i] != nil {
			if err := m.Lower[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("lower" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this mount overlay based on the context it is used
func (m *MountOverlay) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLower(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMountpoint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRef(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpperdir(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkdir(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MountOverlay) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := m.ID.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("id")
		}
		return err
	}

	return nil
}

func (m *MountOverlay) contextValidateLower(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Lower); i++ {

		if m.Lower[i] != nil {
			if err := m.Lower[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("lower" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MountOverlay) contextValidateMountpoint(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "mountpoint", "body", string(m.Mountpoint)); err != nil {
		return err
	}

	return nil
}

func (m *MountOverlay) contextValidateRef(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "ref", "body", int64(m.Ref)); err != nil {
		return err
	}

	return nil
}

func (m *MountOverlay) contextValidateUpperdir(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "upperdir", "body", string(m.Upperdir)); err != nil {
		return err
	}

	return nil
}

func (m *MountOverlay) contextValidateWorkdir(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "workdir", "body", string(m.Workdir)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MountOverlay) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MountOverlay) UnmarshalBinary(b []byte) error {
	var res MountOverlay
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
