// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Name A name is a unique, user-provided identifier for an object.
//
// A name must consist of numbers, letters, and the symbols in the set { `.`, `-`, `_`}.
//
//
// swagger:model name
type Name string

// Validate validates this name
func (m Name) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^[A-Za-z0-1.\-_]*$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this name based on context it is used
func (m Name) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
